version: '3.1'

services:

  geth:
    image: ethereum/client-go
    restart: on-failure
    command: --dev --mine --networkid 17 --wsorigins "*" --ws --dev.period 2 --wsaddr 172.16.1.100 --wsport 18546 --datadir /root/gethnet/datadir --unlock "0x9ca9d2d5e04012c9ed24c0e513c9bfaa4a2dd77f" --ipcdisable --password /run/secrets/node_password
    volumes:
      - ./internal/gethnet/:/root/gethnet
    networks:
      gethnet:
        ipv4_address: 172.16.1.100
    ports: []
    secrets:
      - node_password

  chainlink:
    image: smartcontract/chainlink-sgx
    command: node -d -p /run/secrets/node_password -a /run/secrets/apicredentials
    restart: always
    volumes:
      - ./tools/clroot/:/root/clroot
    environment:
      - LOG_LEVEL=debug
      - ROOT=/root/clroot
      - ETH_HOST=172.16.1.100
      - ETH_CHAIN_ID=17
      - MIN_OUTGOING_CONFIRMATIONS=2
      - MINIMUM_CONTRACT_PAYMENT=1000000000000
      - RUST_BACKTRACE=1
      - CHAINLINK_DEV=true
    networks:
      gethnet:
        ipv4_address: 172.16.1.101
    depends_on:
      - geth
    ports:
      - 6688:6688
    secrets:
      - node_password

networks:
  gethnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0/24

secrets:
  node_password:
    file: ./tools/clroot/password.txt
