
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  source = "github.com/smartcontractkit/gin"
  branch = "staticfs-noroute"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/araddon/dateparse"

[[constraint]]
  name = "github.com/mrwonko/cron"
  branch = "master"

[[constraint]]
  name = "go.uber.org/zap"
  source = "github.com/uber-go/zap"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.5.0"

[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"

[[constraint]]
  name = "gopkg.in/guregu/null.v3"
  version = "3.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.2.1"

[[constraint]]
  name = "go.uber.org/multierr"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jpillora/backoff"
  version = "1.0.0"

[[override]]
  branch = "master"
  name = "github.com/caarlos0/env"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/ugorji/go"
  version = "1.1.4"

[[constraint]]
  name = "github.com/manyminds/api2go"
  version = "1.0-RC4"

[[constraint]]
  branch = "master"
  name = "github.com/willf/pad"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/tevino/abool"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/contrib"

[[constraint]]
  name = "github.com/tidwall/sjson"
  version = "1.0.4"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.23"

[[constraint]]
  branch = "master"
  name = "github.com/unrolled/secure"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[override]]
  name = "github.com/spf13/viper.git"
  version = "1.3.1"

[[override]]
  name = "github.com/mattn/go-sqlite3"
  branch = "master"

[[constraint]]
  name = "github.com/gofrs/flock"
  version = "0.7.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "gopkg.in/gormigrate.v1"
  version = "1.5.0"
