[Database]
# URL is the PostgreSQL URI to connect to your database. Chainlink nodes require Postgres versions >= 11. See
# [Running a Chainlink Node](https://docs.chain.link/docs/running-a-chainlink-node/#set-the-remote-database_url-config) for an example.
#
# Environment variable: `CL_DATABASE_URL`
URL = "postgresql://user:pass@localhost:5432/dbname?sslmode=disable" # Example
# BackupURL is where the automatic database backup will pull from, rather than the main CL_DATABASE_URL. It is recommended
# to set this value to a read replica if you have one to avoid excessive load on the main database.
#
# Environment variable: `CL_DATABASE_BACKUP_URL`
BackupURL = "postgresql://user:pass@read-replica.example.com:5432/dbname?sslmode=disable" # Example
# AllowSimplePasswords skips the password complexity check normally enforced on URL & BackupURL.
#
# Environment variable: `CL_DATABASE_ALLOW_SIMPLE_PASSWORDS`
AllowSimplePasswords = false # Default

# Optional LDAP config
[WebServer.LDAP]
# ServerAddress is the full ldaps:// address of the ldap server to authenticate with and query
ServerAddress = 'ldaps://127.0.0.1' # Example
# ReadOnlyUserLogin is the username of the read only root user used to authenticate the requested LDAP queries 
ReadOnlyUserLogin = 'viewer@example.com' # Example
# ReadOnlyUserPass is the password for the above account
ReadOnlyUserPass = 'password' # Example

[Password]
# Keystore is the password for the node's account.
#
# Environment variable: `CL_PASSWORD_KEYSTORE`
Keystore = "keystore_pass" # Example
# VRF is the password for the vrf keys.
#
# Environment variable: `CL_PASSWORD_VRF`
VRF = "VRF_pass" # Example

[Pyroscope]
# AuthToken is the API key for the Pyroscope server.
#
# Environment variable: `CL_PYROSCOPE_AUTH_TOKEN`
AuthToken = "pyroscope-token" # Example

[Prometheus]
# AuthToken is the authorization key for the Prometheus metrics endpoint.
#
# Environment variable: `CL_PROMETHEUS_AUTH_TOKEN`
AuthToken = "prometheus-token" # Example

[Mercury.Credentials.Name]
# Username is used for basic auth of the Mercury endpoint
Username = "A-Mercury-Username" # Example
# Password is used for basic auth of the Mercury endpoint
Password = "A-Mercury-Password" # Example
# URL is the Mercury endpoint base URL used to access Mercury price feed
URL = "https://example.com" # Example
# LegacyURL is the Mercury legacy endpoint base URL used to access Mercury v0.2 price feed
LegacyURL = "https://example.v1.com" # Example

[Threshold]
# ThresholdKeyShare used by the threshold decryption OCR plugin
ThresholdKeyShare = "A-Threshold-Decryption-Key-Share" # Example
