[Feature]
FeedsManager = true
LogPoller = true

[Log]
Level = 'debug'
JSONConsole = true

[Log.File]
MaxSize = '0b'

[WebServer]
AllowOrigins = '*'
HTTPPort = 6688
SecureCookies = false
HTTPWriteTimeout = '1m'

[WebServer.TLS]
HTTPSPort = 0

[WebServer.RateLimit]
Authenticated = 2000
Unauthenticated = 1000

[OCR2]
Enabled = true

[OCR]
Enabled = false

[P2P]
IncomingMessageBufferSize = 13
OutgoingMessageBufferSize = 17
TraceLogging = true

[P2P.V2]
Enabled = true
ListenAddresses = ['0.0.0.0:5001']
AnnounceAddresses = ['0.0.0.0:5001']
DeltaDial = '500ms'
DeltaReconcile = '5s'

[[EVM]] # Geth_1337 Private Blockchain
ChainID = '1337'

[[EVM.Nodes]]
Name = 'Geth_1337 Container'
WSURL = 'ws://geth_1337:8546'
HTTPURL = 'http://geth_1337:8545'

[[EVM]]
ChainID = '2337'

[[EVM.Nodes]]
Name = 'Geth_2337 Container'
WSURL = 'ws://geth_2337:8546'
HTTPURL = 'http://geth_2337:8545'

[[EVM]] # Eth Sepolia Testnet
ChainID = '11155111'
LinkContractAddress = '0x779877A7B0D9E8603169DdbD7836e478b4624789'

[[EVM.Nodes]]
Name = 'primary-0-11155111'
WSURL = 'wss://rpcs.main.stage.cldev.sh/ethereum/sepolia'
HTTPURL = 'https://rpcs.main.stage.cldev.sh/ethereum/sepolia'

[[EVM]] # Avalanche Fuji Testnet
ChainID = '43113'
LinkContractAddress = '0x0b9d5D9136855f6FEc3c0993feE6E9CE8a297846'

[[EVM.Nodes]]
Name = 'primary-0-43113'
WSURL = 'wss://rpcs.main.stage.cldev.sh/avalanche/fuji'
HTTPURL = 'https://rpcs.main.stage.cldev.sh/avalanche/fuji'

[[EVM]] # BSC Testnet
ChainID = '97'
LinkContractAddress = '0x84b9B910527Ad5C03A9Ca831909E21e236EA7b06'

[[EVM.Nodes]]
Name = 'primary-0-97'
WSURL = 'wss://rpcs.main.stage.cldev.sh/bsc/testnet'
HTTPURL = 'https://rpcs.main.stage.cldev.sh/bsc/testnet'

