ChainID = '421613'
ChainType = 'arbitrum'
LinkContractAddress = "0x615fBe6372676474d9e6933d310469c9b68e9726"
OCR.ContractConfirmations = 1

[HeadTracker]
BlockEmissionIdleWarningThreshold = '0'

[NodePool]
NoNewHeadsThreshold = '0'
