ChainID = '421611'
ChainType = 'arbitrum'
LinkContractAddress = "0x615fBe6372676474d9e6933d310469c9b68e9726"
OCR.ContractConfirmations = 1

[GasEstimator]
BumpThreshold = '0'
Mode = 'FixedPrice'
LimitDefault = 7000000
LimitTransfer = 800000
PriceDefault = '1000 gwei'
PriceMaxWei = '1000 gwei'
PriceMinWei = '1000 gwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 0

[HeadTracker]
BlockEmissionIdleWarningThreshold = '0'

[NodePool]
NoNewHeadsThreshold = '0'
