ChainID = '1'
LinkContractAddress = '0x514910771AF9Ca656af840dff83E8264EcF986CA'
MinimumContractPayment = '0.1 link'
OperatorFactoryAddress = '0x3E64Cd889482443324F91bFA9c84fE72A511f48A'

[GasEstimator]
EIP1559DynamicFees = true

[GasEstimator.BlockHistory]
BatchSize = 4
BlockDelay = 1
BlockHistorySize = 4
TransactionPercentile = 50
