ChainID = '250'
LinkContractAddress = '0x6F43FF82CCA38001B6699a8AC47A2d0E66939407'
LogPollInterval = '1s'
MinIncomingConfirmations = 3

[GasEstimator]
PriceDefault = '15 gwei'
PriceMaxWei = '0.2 milli'

[HeadTracker]
BlockEmissionIdleWarningThreshold = '15s'

[NodePool]
NoNewHeadsThreshold = '30s'
