[CCIP]

[CCIP.Groups.load]
NetworkPairs = ['SEPOLIA,ARBITRUM_SEPOLIA','SEPOLIA,OPTIMISM_GOERLI','SEPOLIA,POLYGON_MUMBAI','AVALANCHE_FUJI,SEPOLIA','SEPOLIA,BASE_GOERLI','SEPOLIA,BSC_TESTNET','SEPOLIA,WEMIX_TESTNET','AVALANCHE_FUJI,OPTIMISM_GOERLI','AVALANCHE_FUJI,POLYGON_MUMBAI','AVALANCHE_FUJI,BSC_TESTNET','AVALANCHE_FUJI,BASE_GOERLI','OPTIMISM_GOERLI,BASE_GOERLI','OPTIMISM_GOERLI,POLYGON_MUMBAI','BSC_TESTNET,POLYGON_MUMBAI','BSC_TESTNET,BASE_GOERLI','WEMIX_TESTNET,KROMA_SEPOLIA']
MsgType = 'WithoutToken'
PhaseTimeout = '50m'
TestDuration = '1m'
ExistingDeployment = true
RequestPerUnitTime = [1]
TimeUnit = '5m'
NoOfTokensPerChain = 1
NoOfTokensInMsg = 1
AmountPerToken = 1
TestRunName = 'prod-testnet-2.7.1-ccip1.2.2-beta'

[CCIP.Groups.smoke]
MsgType = 'WithoutToken'
NetworkPairs = ['SEPOLIA,ARBITRUM_SEPOLIA','SEPOLIA,OPTIMISM_GOERLI','SEPOLIA,POLYGON_MUMBAI','AVALANCHE_FUJI,SEPOLIA','SEPOLIA,BASE_GOERLI','SEPOLIA,BSC_TESTNET','SEPOLIA,WEMIX_TESTNET','AVALANCHE_FUJI,OPTIMISM_GOERLI','AVALANCHE_FUJI,POLYGON_MUMBAI','AVALANCHE_FUJI,BSC_TESTNET','AVALANCHE_FUJI,BASE_GOERLI','OPTIMISM_GOERLI,BASE_GOERLI','OPTIMISM_GOERLI,POLYGON_MUMBAI','BSC_TESTNET,POLYGON_MUMBAI','BSC_TESTNET,BASE_GOERLI','WEMIX_TESTNET,KROMA_SEPOLIA']
PhaseTimeout = '50m'
LocalCluster = false
ExistingDeployment = true
ReuseContracts = true
NoOfTokensPerChain = 1
NoOfTokensInMsg = 1

