ChainID = '44787'
ChainType = 'celo'
FinalityDepth = 10
LogPollInterval = '5s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '1m'
OCR.ContractConfirmations = 1

[GasEstimator]
PriceDefault = '5 gwei'
PriceMax = '500 gwei'
PriceMin = '5 gwei'
BumpMin = '2 gwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[HeadTracker]
HistoryDepth = 50
