ChainID = '1'
LinkContractAddress = '0x514910771AF9Ca656af840dff83E8264EcF986CA'
MinContractPayment = '0.1 link'
OperatorFactoryAddress = '0x3E64Cd889482443324F91bFA9c84fE72A511f48A'

[GasEstimator]
EIP1559DynamicFees = true

[GasEstimator.BlockHistory]
# EIP-1559 does well on a smaller block history size
BlockHistorySize = 4
TransactionPercentile = 50

[OCR2.Automation]
GasLimit = 10500000
