ChainID = '588'
ChainType = 'metis'
FinalityDepth = 1
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '0'
OCR.ContractConfirmations = 1

[BalanceMonitor]
Enabled = true

[GasEstimator]
Mode = 'SuggestedPrice'
PriceMin = '0'
BumpThreshold = 3

[GasEstimator.BlockHistory]
BlockHistorySize = 0

[NodePool]
SyncThreshold = 10
