# Metis is an L2 chain based on Optimism.
ChainID = '1088'
ChainType = 'metis'
# Sequencer offers absolute finality
FinalityDepth = 1
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '0'
OCR.ContractConfirmations = 1

[GasEstimator]
Mode = 'L2Suggested'
# Metis uses the L2Suggested estimator; we don't want to place any limits on the minimum gas price
PriceMin = '0'
# Never bump gas on metis
BumpThreshold = 0

[BalanceMonitor]
Enabled = true

[GasEstimator.BlockHistory]
# Force an error if someone enables the estimator by accident; we never want to run the block history estimator on metisaa
BlockHistorySize = 0

[NodePool]
SyncThreshold = 10
