ChainID = '59902'
ChainType = 'optimismBedrock'
FinalityTagEnabled = true
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '0'

[GasEstimator]
Mode = 'SuggestedPrice'
PriceMin = '0'
LimitDefault = 8000000

[GasEstimator.BlockHistory]
BlockHistorySize = 0

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1
