ChainID = '80001'
FinalityDepth = 500
FinalityTagEnabled = true
LinkContractAddress = '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
LogPollInterval = '1s'
MinIncomingConfirmations = 5
NoNewHeadsThreshold = '30s'
RPCBlockQueryDelay = 10
RPCDefaultBatchSize = 100

[Transactions]
MaxQueued = 5000

[GasEstimator]
PriceDefault = '25 gwei'
PriceMax = '115792089237316195423570985008687907853269984665.640564039457584007913129639935 tether'
PriceMin = '25 gwei'
BumpMin = '20 gwei'
BumpThreshold = 5

[GasEstimator.BlockHistory]
BlockHistorySize = 24

[HeadTracker]
HistoryDepth = 2000

[NodePool]
SyncThreshold = 10
