ChainID = '1442'
FinalityDepth = 1
NoNewHeadsThreshold = '12m'
MinIncomingConfirmations = 1
OCR.ContractConfirmations = 1
LogPollInterval = '30s'

[Transactions]
ResendAfterThreshold = '3m'

[GasEstimator]
PriceMin = '50 mwei'
BumpPercent = 40
BumpMin = '20 mwei'

[GasEstimator.BlockHistory]
BlockHistorySize = 12

[HeadTracker]
HistoryDepth = 50