# This file contains all secret parameters for ccip tests.
# DO NOT UPDATE THIS FILE WITH ANY SECRET VALUES.
# Use this file as a template for the actual secret file and update all the parameter values accordingly.
# DO NOT COMMIT THE ACTUAL SECRET FILE TO THE REPOSITORY.
[CCIP]
[CCIP.Env]

# ChainlinkImage is mandatory for all tests.
[CCIP.Env.NewCLCluster]
[CCIP.Env.NewCLCluster.Common]
[CCIP.Env.NewCLCluster.Common.ChainlinkImage]
image = "chainlink-ccip"
version = "latest"

# Networks configuration with rpc urls and wallet keys are mandatory only for tests running on live networks
# The following example is for 3 networks: Ethereum, Base and Arbitrum
# Network configuration can be ignored for tests running on simulated/private networks
[CCIP.Env.Network]
selected_networks= [
    'ETHEREUM_MAINNET','BASE_MAINNET', 'ARBITRUM_MAINNET',
]

[CCIP.Env.Network.RpcHttpUrls]
ETHEREUM_MAINNET = ['<https for ethereum network>', '<https for ethereum network>']
BASE_MAINNET = ['<https for base network>', '<https for base network>']
ARBITRUM_MAINNET = ['<https for arbitrum network>', '<https for arbitrum network>']

[CCIP.Env.Network.RpcWsUrls]
ETHEREUM_MAINNET = ['<wss for ethereum network>', '<wss for ethereum network>']
BASE_MAINNET = ['<wss for base network>', '<wss for base network>']
ARBITRUM_MAINNET = ['<wss for arbitrum network>', '<wss for arbitrum network>']

[CCIP.Env.Network.WalletKeys]
ETHEREUM_MAINNET = ['<private key for ethereum network>']
BASE_MAINNET = ['<private key for base network>']
ARBITRUM_MAINNET = ['<private key for arbitrum network>']


# Chainlink upgrade image is used only for upgrade tests
#[CCIP.Env.NewCLCluster.Common.ChainlinkUpgradeImage]
#image = "***.dkr.ecr.***.amazonaws.com/chainlink-ccip"
#version = "****"

# Used for tests using 1. loki logging for test results.
# Mandatory for load tests
[CCIP.Env.Logging.Loki]
tenant_id="<tenant id for loki>"
endpoint="<url for loki>"

[CCIP.Env.Logging.Grafana]
base_url="<url for grafana>"
dashboard_url="/d/6vjVx-1V8/ccip-long-running-tests"
