
[Common]
minimum_confirmations = 1

[NewEnvConfig]
sub_funds_link = 1
node_sending_key_funding = 10

[ExistingEnvConfig]
coordinator_address = "0x50d47e4142598E3411aA864e08a44284e471AC6f"
#consumer_address = "0x087F232165D9bA1A602f148025e5D0666953F64a"
#sub_id = "52116875585187328970776211988181422347535732407068188096422095950800466618218"
key_hash = "0x027f94ff1465b3525f9fc03e9ff7d6d2c0953482246dd6ae07570c45d6631414"
create_fund_subs_and_add_consumers = true
link_address = "0xb1D4538B4571d411F07960EF2838Ce337FE1E80E"
sub_funds_link = 50
node_sending_key_funding_min = 3
node_sending_keys = [
    "0x3d659dE506d3b22e7660d579327126221EfB2651",
    "0x7cAF21fA7423b3f4Ec15f87C7BBa83aE8cA4bDf3",
    "0x8E1aDA97ac6883E8D7738E2dB9cC1A32211d3429",
    "0xA4fdfE2c9438fd8388C2837c0AB199946f8041D3",
    "0xb4CC2d6f933244Ff596dd1A7aB6E96769d237B3b",
    "0xded252Eb0caA71aFABab6a0fd948eA9CaAdf7012",
]

# 10 RPM - 1 tx request with 1 rand request in each tx every 6 seconds
[Soak]
rate_limit_unit_duration = "6s"
rps = 1
randomness_request_count_per_request = 1 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

# approx 60 RPM - 1 tx request with 4 rand requests in each tx every 3 seconds
[Load]
rate_limit_unit_duration = "3s"
rps = 1
randomness_request_count_per_request = 3 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 2 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

# approx 540 RPM - 3 tx requests per second with 4 rand requests in each tx
[Stress]
rate_limit_unit_duration = "1s"
rps = 3
randomness_request_count_per_request = 4 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1

# approx 150 RPM - 1 tx request with 150 rand requests in each tx every 60 seconds
[Spike]
rate_limit_unit_duration = "1m"
rps = 1
randomness_request_count_per_request = 150 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1