[[EVM]]
ChainID = '0'
Enabled = false
BlockBackfillDepth = 5
BlockBackfillSkip = true
ChainType = 'foobar'
FinalityDepth = 50
FlagsContractAddress = '0x538aAaB4ea120b2bC2fe5D296852D948F07D849e'
LinkContractAddress = '0xa5B85635Be42F21f94F28034B7DA440EeFF0F418'
LogBackfillBatchSize = 200
LogPollInterval = '10s'
MinIncomingConfirmations = 12
MinContractPayment = '123456789'
NonceAutoSync = true
NoNewHeadsThreshold = '5m0s'
OperatorFactoryAddress = '0xae4E781a6218A8031764928E88d457937A954fC3'
RPCDefaultBatchSize = 10
RPCBlockQueryDelay = 6

[EVM.Transactions]
ForwardersEnabled = true
MaxInFlight = 1000
MaxQueued = 1500
ReaperInterval = '10h0m0s'
ReaperThreshold = '1m0s'
ResendAfterThreshold = '5m0s'

[EVM.BalanceMonitor]
Enabled = true

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '100.2 kwei'
PriceMax = '9 mwei'
LimitDefault = 102030405
LimitMax = 1020304050
LimitMultiplier = '1.003'
LimitTransfer = 4294967295
BumpMin = '987.654 kwei'
BumpPercent = 2
BumpThreshold = 10
BumpTxDepth = 7
EIP1559DynamicFees = true
FeeCapDefault = '45.678912345 gwei'
TipCapDefault = '4.321 kwei'
TipCapMin = '7 wei'

[EVM.GasEstimator.LimitJobType]
OCR = 9901
DR = 9902
VRF = 9903
FM = 9904
Keeper = 9905

[EVM.GasEstimator.BlockHistory]
BatchSize = 13
BlockHistorySize = 56
EIP1559FeeCapBufferBlocks = 97
TransactionPercentile = 42

[EVM.HeadTracker]
HistoryDepth = 7
MaxBufferSize = 50
SamplingInterval = '5s'

[EVM.NodePool]
PollFailureThreshold = 3
PollInterval = '1m0s'
SelectionMode = 'HighestHead'

[[EVM.Nodes]]
Name = 'primary_0_1'
WSURL = 'ws://test1.invalid'

[[EVM.Nodes]]
Name = 'primary_0_2'
WSURL = 'ws://test2.invalid'
HTTPURL = 'https://test2.invalid'

[[EVM.Nodes]]
Name = 'sendonly_0_1'
HTTPURL = 'http://test5.invalid'
SendOnly = true

[[EVM]]
ChainID = '42'
Enabled = false
BlockBackfillDepth = 5
BlockBackfillSkip = true
FinalityDepth = 50
FlagsContractAddress = '0x538aAaB4ea120b2bC2fe5D296852D948F07D849e'
LinkContractAddress = '0xa5B85635Be42F21f94F28034B7DA440EeFF0F418'
LogBackfillBatchSize = 200
LogPollInterval = '10s'
MinIncomingConfirmations = 12
MinContractPayment = '123456789'
NonceAutoSync = true
NoNewHeadsThreshold = '5m0s'
OperatorFactoryAddress = '0xae4E781a6218A8031764928E88d457937A954fC3'
RPCDefaultBatchSize = 10
RPCBlockQueryDelay = 6

[EVM.Transactions]
ForwardersEnabled = true
MaxInFlight = 1000
MaxQueued = 1500
ReaperInterval = '10h0m0s'
ReaperThreshold = '1m0s'
ResendAfterThreshold = '5m0s'

[EVM.BalanceMonitor]
Enabled = true

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '100.2 kwei'
LimitDefault = 102030405
LimitMax = 1020304050
LimitMultiplier = '1.003'
LimitTransfer = 4294967295
BumpMin = '987.654 kwei'
BumpPercent = 2
BumpThreshold = 10
BumpTxDepth = 7
EIP1559DynamicFees = true
FeeCapDefault = '45.678912345 gwei'

[EVM.GasEstimator.LimitJobType]
OCR = 9901
DR = 9902
VRF = 9903
FM = 9904
Keeper = 9905

[EVM.GasEstimator.BlockHistory]
BatchSize = 13
BlockHistorySize = 56
EIP1559FeeCapBufferBlocks = 97
TransactionPercentile = 42

[EVM.HeadTracker]
HistoryDepth = 7
MaxBufferSize = 50
SamplingInterval = '5s'

[EVM.NodePool]
PollFailureThreshold = 3
PollInterval = '1m0s'
SelectionMode = 'HighestHead'

[[EVM.Nodes]]
Name = 'primary_42_1'
WSURL = 'ws://test6.invalid'

[[EVM]]
ChainID = '43'
BlockBackfillDepth = 5
BlockBackfillSkip = true
FinalityDepth = 50
FlagsContractAddress = '0x538aAaB4ea120b2bC2fe5D296852D948F07D849e'
LinkContractAddress = '0xa5B85635Be42F21f94F28034B7DA440EeFF0F418'
LogBackfillBatchSize = 200
LogPollInterval = '10s'
MinIncomingConfirmations = 12
MinContractPayment = '123456789'
NonceAutoSync = true
NoNewHeadsThreshold = '5m0s'
OperatorFactoryAddress = '0xae4E781a6218A8031764928E88d457937A954fC3'
RPCDefaultBatchSize = 10
RPCBlockQueryDelay = 6

[EVM.Transactions]
ForwardersEnabled = true
MaxInFlight = 1000
MaxQueued = 1500
ReaperInterval = '10h0m0s'
ReaperThreshold = '1m0s'
ResendAfterThreshold = '5m0s'

[EVM.BalanceMonitor]
Enabled = true

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '100.2 kwei'
LimitDefault = 102030405
LimitMax = 1020304050
LimitMultiplier = '1.003'
LimitTransfer = 4294967295
BumpMin = '987.654 kwei'
BumpPercent = 2
BumpThreshold = 10
BumpTxDepth = 7
EIP1559DynamicFees = true
FeeCapDefault = '45.678912345 gwei'

[EVM.GasEstimator.LimitJobType]
OCR = 9901
DR = 9902
VRF = 9903
FM = 9904
Keeper = 9905

[EVM.GasEstimator.BlockHistory]
BatchSize = 13
BlockHistorySize = 56
EIP1559FeeCapBufferBlocks = 97
TransactionPercentile = 42

[EVM.HeadTracker]
HistoryDepth = 7
MaxBufferSize = 50
SamplingInterval = '5s'

[EVM.NodePool]
PollFailureThreshold = 3
PollInterval = '1m0s'
SelectionMode = 'HighestHead'

[[EVM.Nodes]]
Name = 'sendonly_43_1'
HTTPURL = 'http://test7.invalid'
SendOnly = true

[[EVM]]
ChainID = '1337'
Enabled = false
BlockBackfillDepth = 5
BlockBackfillSkip = true
FinalityDepth = 50
FlagsContractAddress = '0x538aAaB4ea120b2bC2fe5D296852D948F07D849e'
LinkContractAddress = '0xa5B85635Be42F21f94F28034B7DA440EeFF0F418'
LogBackfillBatchSize = 200
LogPollInterval = '10s'
MinIncomingConfirmations = 12
MinContractPayment = '123456789'
NonceAutoSync = true
NoNewHeadsThreshold = '5m0s'
OperatorFactoryAddress = '0xae4E781a6218A8031764928E88d457937A954fC3'
RPCDefaultBatchSize = 10
RPCBlockQueryDelay = 6

[EVM.Transactions]
ForwardersEnabled = true
MaxInFlight = 1000
MaxQueued = 1500
ReaperInterval = '10h0m0s'
ReaperThreshold = '1m0s'
ResendAfterThreshold = '5m0s'

[EVM.BalanceMonitor]
Enabled = true

[EVM.GasEstimator]
Mode = 'FixedPrice'
PriceDefault = '100.2 kwei'
LimitDefault = 102030405
LimitMax = 1020304050
LimitMultiplier = '1.003'
LimitTransfer = 4294967295
BumpMin = '987.654 kwei'
BumpPercent = 2
BumpThreshold = 10
BumpTxDepth = 7
EIP1559DynamicFees = true
FeeCapDefault = '45.678912345 gwei'

[EVM.GasEstimator.LimitJobType]
OCR = 9901
DR = 9902
VRF = 9903
FM = 9904
Keeper = 9905

[EVM.GasEstimator.BlockHistory]
BatchSize = 13
BlockHistorySize = 56
EIP1559FeeCapBufferBlocks = 97
TransactionPercentile = 42

[EVM.HeadTracker]
HistoryDepth = 7
MaxBufferSize = 50
SamplingInterval = '5s'

[EVM.NodePool]
PollFailureThreshold = 3
PollInterval = '1m0s'
SelectionMode = 'HighestHead'

[[EVM.Nodes]]
Name = 'primary_1337_1'
WSURL = 'ws://test3.invalid'
HTTPURL = 'http://test3.invalid'

[[EVM.Nodes]]
Name = 'sendonly_1337_1'
HTTPURL = 'http://test4.invalid'
SendOnly = true
