[Database]
# URL is the PostgreSQL URI to connect to your database. Chainlink nodes require Postgres versions >= 11. See
# [Running a Chainlink Node](https://docs.chain.link/docs/running-a-chainlink-node/#set-the-remote-database_url-config) for an example.
#
# Environment variable: `CL_DATABASE_URL`
URL = "postgresql://user:pass@localhost:5432/dbname?sslmode=disable" # Example
# BackupURL is where the automatic database backup will pull from, rather than the main CL_DATABASE_URL. It is recommended
# to set this value to a read replica if you have one to avoid excessive load on the main database.
#
# Environment variable: `CL_DATABASE_BACKUP_URL`
BackupURL = "postgresql://user:pass@read-replica.example.com:5432/dbname?sslmode=disable" # Example
# AllowSimplePasswords skips the password complexity check normally enforced on URL & BackupURL.
#
# Environment variable: `CL_DATABASE_ALLOW_SIMPLE_PASSWORDS`
AllowSimplePasswords = false # Default

[Explorer]
# AccessKey is the access key for authenticating with the Explorer.
#
# Environment variable: `CL_EXPLORER_ACCESS_KEY`
AccessKey = "access_key" # Example
# Secret is the secret for authenticating with the Explorer.
#
# Environment variable: `CL_EXPLORER_SECRET`
Secret = "secret" # Example

[Password]
# Keystore is the password for the node's account.
#
# Environment variable: `CL_PASSWORD_KEYSTORE`
Keystore = "keystore_pass" # Example
# VRF is the password for the vrf keys.
#
# Environment variable: `CL_PASSWORD_VRF`
VRF = "VRF_pass" # Example

[Pyroscope]
# AuthToken is the API key for the Pyroscope server.
#
# Environment variable: `CL_PYROSCOPE_AUTH_TOKEN`
AuthToken = "pyroscope-token" # Example

[Prometheus]
# AuthToken is the authorization key for the Prometheus metrics endpoint.
#
# Environment variable: `CL_PROMETHEUS_AUTH_TOKEN`
AuthToken = "prometheus-token" # Example
