build: false

clone_folder: c:\chainlink

deploy: false

environment:
  CC: gcc.exe
  CGO_ENABLED: 1
  GOPATH: c:\gopath
  GOVERSION: 1.12.6
  MSYS2_ARCH: x86_64
  MSYS2_BITS: 64
  MSYSTEM: MINGW64
  PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
  nodejs_version: "10"
  PYTHON: "3.7"

stack: python %PYTHON%

init:
  - git config --global core.autocrlf input

install:
  # Install the configured nodejs version
  - ps: Install-Product node $env:nodejs_version
  # Generate solidity contract artifacts
  - yarn install
  - yarn workspace chainlink build:windows

  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;C:\msys64\mingw64\bin\;%Path%
  # Check tools exist.
  - gcc --version
  - go version
  - go env
  - go mod download

test_script:
  - go test -parallel 2 -p 1 ./...
