[Network]
selected_networks = ["ARBITRUM_SEPOLIA"]

[ARBITRUM_SEPOLIA.VRFv2Plus.General]
use_existing_env = true

[ARBITRUM_SEPOLIA.VRFv2Plus.ExistingEnv]
coordinator_address = "0xF7ba1Cf141F9729abC43c146dc2bf86EbcfD8603"
consumer_address = ""
sub_id = ""
key_hash = "0xe13aa26fe94bfcd2ae055911f4d3bf1aed54ca6cf77af34e17f918802fd69ba1"
create_fund_subs_and_add_consumers = true
node_sending_key_funding_min = 20
node_sending_keys = [
    "0xbE21ae371FcA1aC2d8A152e707D21e68d7d99252",
    "0xb13e9BA0aE94FD3b89B13b092e6d41614c805134",
    "0x27aa703e585Ee165B7c977EAA652eCFa13b08294",
    "0x9324643ACD2ec5b0813488E5EdAb64C3758ae4Ee",
    "0x7CBA8c8e86f23f23363051650Fe5AE4DE78c3652",
    "0x9A0143a4BAB55A826331A8ef82462557633aA016",
    "0xD4259633F8e87949F683433a17e1fFcCE27865AC",
    "0x5e47B71d6F95f68cd5538907ec6A9635b1Fe30Fa",
    "0xa850a1a257FDF439c8f854ce3b89dd5b6F411827",
    "0x7c82D56087c10aF2c3970f9a9Be7786B2850ce91",
    "0x9545CB59956347d3debf27f5029754bBE1d398FA",
    "0xEb8C69ac19709f27A97FB4A561f51AD2F9b34c5B",
    #   BHS
    "0xf0e8cF7Fbd28Fc4D412B76B744CDA269df671F8e",
    "0x317A02A658d12E5Bb4A6270171E7385928dD2d53",
    "0x480f1dbcEc118Bd91e4dbb7e45bFa4A73180d21f",
    "0x500a2662FaF981EC4669f791349D37Cbf1bE7d85",
    "0x2ad350374B904c10B47c64ECdBD9e70BB0833Be2",
    "0x0b946F0bF4e63C12b5157137f1c130f0788bC1b1",
    #    BHF
    "0x571BBF4a5b07fc3F47Bd3B65CE2FE73739f86623"
]
