version: '3.5'

services:
  node:
    depends_on:
      - devnet
  node-2:
    depends_on:
      - devnet
  devnet:
    container_name: parity
    image: smartcontract/dev:devnet-openethereum-2
    user: root
    command: --reseal-max-period 4000 --force-sealing --config /devnet/miner.toml --db-path /devnet/database
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - parity-db-data:/devnet/database
volumes:
  parity-db-data:
