version: '3.1'

services:
  wait-db:
    container_name: wait-for-db
    build:
      context: .
      dockerfile: wait-postgres.Dockerfile
    command: '-h node-db -p 5432 -U postgres -d $CHAINLINK_DB_NAME --timeout=150'
    depends_on:
      - node-db
volumes:
  node-db-data:
