name: Bash Scripts

on:
  push:
    branches:
      - this-workflow-is-disabled-for-ccip

jobs:
  changes:
    name: detect changes
    runs-on: ubuntu-latest
    outputs:
      bash-scripts-src: ${{ steps.bash-scripts.outputs.src }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: bash-scripts
        with:
          filters: |
            src:
            - 'tools/bin/**'
            - '.github/workflows/bash-scripts.yml'
  shellcheck:
    name: ShellCheck Lint
    runs-on: ubuntu-latest
    needs: [changes]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run ShellCheck
        if: needs.changes.outputs.bash-scripts-src == 'true'
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          scandir: "./tools/bin"
          # Consider changing this to check for warnings once all warnings are fixed.
          severity: error
