name: 'Build Chainlink'

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build-chainlink:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

      - name: Build chainlink image
        uses: ./.github/actions/build-sign-publish-chainlink
        with:
          publish: false
          sign-images: false
