name: 'Build Chainlink'

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build-chainlink:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Build chainlink image
        uses: ./.github/actions/build-sign-publish-chainlink
        with:
          build-root: true
          build-nonroot: true
          publish-root: false
          publish-nonroot: false
          sign-images: false
      - name: Collect Metrics
        if: always()
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@808c183d1f5c26a4f3fd50b75d3cf7b58d9aa293
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: build-chainlink
        continue-on-error: true
