# This is reusable workflow that is helpful if you wish to check integration against chainlink repo from another repo with custom deps
name: Custom image build
on:
  workflow_dispatch:
    inputs:
      cl_ref:
        description: chainlink commit or branch
        required: true
        default: develop
        type: string
      dep_solana_sha:
        description: chainlink-solana commit or branch
        required: false
        default: develop
        type: string
      dep_terra_sha:
        description: chainlink-terra commit or branch
        required: false
        default: main
        type: string
      dep_starknet_sha:
        description: chainlink-starknet commit or branch
        required: false
        default: main
        type: string
  workflow_call:
    inputs:
      cl_repo:
        required: true
        description: The chainlik ecr repository to use
        default: ${{ github.repository }}
        type: string
      cl_ref:
        required: false
        description: The git ref from cl to use
        default: develop
        type: string
      dep_solana_sha:
        required: false
        description: chainlink-solana commit or branch
        type: string
      dep_terra_sha:
        required: false
        description: chainlink-terra commit or branch
        type: string
      dep_starknet_sha:
        required: false
        description: chainlink-starknet commit or branch
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: The AWS access key id to use
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: The AWS secret key to use
      AWS_REGION:
        required: true
        description: The AWS region to use
      AWS_ROLE_TO_ASSUME:
        required: true
        description: The AWS role to assume
      QA_KUBECONFIG:
        required: true
        description: The kubernetes configuation to use
      QA_PRIVATE_GHA_PULL:
        required: false
        description: Token to pull private repos
jobs:
  build-chainlink:
    name: Build Chainlink Image
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/smartcontractkit/chainlink-starknet
      GH_ACCESS_TOKEN: ${{ secrets.QA_PRIVATE_GHA_PULL }}
    steps:
      - name: Checkout Chainlink repo
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.cl_repo }}
          ref: ${{ github.event.inputs.cl_ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - name: Replace GHA URL
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Replace Solana deps manual flow
        if: ${{ github.event.inputs.dep_solana_sha }}
        run: |
          go get github.com/smartcontractkit/chainlink-solana@${{ github.event.inputs.dep_solana_sha }}
      - name: Replace Terra deps manual flow
        if: ${{ github.event.inputs.dep_terra_sha }}
        run: |
          go get github.com/smartcontractkit/chainlink-terra@${{ github.event.inputs.dep_terra_sha }}
      - name: Replace StarkNet deps manual flow
        if: ${{ github.event.inputs.dep_starknet_sha }}
        run: |
          go get github.com/smartcontractkit/chainlink-starknet@${{ github.event.inputs.dep_starknet_sha }}
      - name: Replace Solana deps workflow_call
        if: ${{ inputs.dep_solana_sha }}
        run: |
          go get github.com/smartcontractkit/chainlink-solana@${{ inputs.dep_solana_sha }}
      - name: Replace Terra deps workflow_call
        if: ${{ inputs.dep_terra_sha }}
        run: |
          go get github.com/smartcontractkit/chainlink-terra@${{ inputs.dep_terra_sha }}
      - name: Replace StarkNET deps workflow_call
        if: ${{ inputs.dep_starknet_sha }}
        run: |
          go get github.com/smartcontractkit/chainlink-starknet@${{ inputs.dep_starknet_sha }}
      - name: Tidy
        run: |
          go mod tidy
      - name: Env vars
        run: env
      - name: Cat go.mod
        run: cat go.mod
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/chainlink.Dockerfile
          # comma separated like: KEY1=VAL1,KEY2=VAL2,...
          build-args: COMMIT_SHA=${{ github.sha }}
          tags: 795953128386.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/chainlink:custom.${{ github.sha }}
          push: true
