#
# This action checks PRs to see if any CHANGELOG* files were updated.
# If none were, it will add a message to the PR asking if it would make sense to do so.
#
name: Changelog

on: pull_request

jobs:
  changelog:
    name: Changelog checker
    runs-on: ubuntu-latest
    steps:
      - name: Check for changed files
        id: changedfiles
        uses: futuratrepadeira/changed-files@186b5b30b1f5e44ed655a59652746c3ce00d53ef # Version v3.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '^docs/CHANGELOG.*$'
      - name: Make a comment
        uses: unsplash/comment-on-pr@d1a1d5dd1eb1bb657a01f4d92dd5e4d5bb7857d3 # Version v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if:
          contains(steps.changedfiles.outputs.files_updated, 'CHANGELOG') != true && contains(steps.changedfiles.outputs.files_created, 'CHANGELOG') != true
        with:
          msg: "I see that you haven't updated any CHANGELOG files. Would it make sense to do so?"
          check_for_duplicate_msg: false
