name: chaincli CI

on:
  push:
    paths:
      - "core/scripts/chaincli/**"
  pull_request:
    paths:
      - "core/scripts/chaincli/**"

jobs:
  golangci:
    if: ${{ github.event_name == 'pull_request' ||  github.event_name == 'schedule' }}
    name: chaincli-lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Golang Lint
        uses: ./.github/actions/golangci-lint
        with:
          name: chaincli-lint
          go-directory: core/scripts/chaincli
          go-version-file: core/scripts/go.mod
          go-module-file: core/scripts/go.sum
          gc-basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          gc-host: ${{ secrets.GRAFANA_CLOUD_HOST }}
