#
# This action creates or updates a Release Preview PR that shows which changes are going to be part of the next release
# when a PR is merged into develop branch
#

name: Release Preview - Changeset

on:
  push:
    branches:
      - develop

jobs:
  cicd-changesets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changeset-added
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            core-changeset:
              - added: '.changeset/**'

      - name: cicd-changesets
        if: steps.changeset-added.outputs.core-changeset == 'true'
        uses: smartcontractkit/.github/actions/cicd-changesets@6da79c7b9f14bec077df2c1ad40d53823b409d9c # cicd-changesets@0.3.3
        with:
          # general inputs
          git-user: app-token-issuer-releng[bot]
          git-email: app-token-issuer-releng[bot]@users.noreply.github.com
          pnpm-use-cache: false
          pr-draft: true
          pr-title: "[DO NOT MERGE] Release Preview - Changeset"
          # aws inputs
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_OIDC_CHAINLINK_CI_AUTO_PR_TOKEN_ISSUER_ROLE_ARN }}
          aws-lambda-url: ${{ secrets.AWS_INFRA_RELENG_TOKEN_ISSUER_LAMBDA_URL }}
          # grafana inputs
          gc-basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
          gc-host: ${{ secrets.GRAFANA_INTERNAL_HOST }}
          gc-org-id: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
