name: 'SigScanner Check'

on:
  push:

jobs:

  sigscanner-check:

    runs-on: ubuntu-latest
    steps:
      - run: echo "üîé Checking commit ${{ github.sha }} by ${{ github.actor }} in ${{ github.repository }} - ${{ github.event_name }}"
      - run: |
          CODE=`curl --write-out '%{http_code}' -X POST -H "Content-Type: application/json" -H "Authorization: $API_TOKEN" --silent --output /dev/null --url "$API_URL" --data '{"commit":"${{ github.sha }}","repository":"${{ github.repository }}","author":"${{ github.actor }}"}'`
          echo "Received $CODE"
          if [[ "$CODE" == "200" ]]; then
            echo "‚úÖ Commit is verified"
            exit 0
          else
            echo "‚ùå Commit is NOT verified"
            exit 1
          fi
        env:
          API_TOKEN: ${{ secrets.SIGSCANNER_API_TOKEN }}
          API_URL: ${{ secrets.SIGSCANNER_API_URL }}
