name: golang/static
on: pull_request
jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go mod download
      - run: go vet ./...
  shadow:
    name: shadow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go get -v golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      - run: go mod download
      - run: go vet -vettool=$HOME/go/bin/shadow ./...
  bodyclose:
    name: bodyclose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go get -v github.com/timakin/bodyclose
      - run: go mod download
      - run: go vet -vettool=$HOME/go/bin/bodyclose ./...
  imports:
    name: imports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go get -v golang.org/x/tools/cmd/goimports
      - run: d="$($HOME/go/bin/goimports -d ./)" && if [ -n "$d" ]; then echo "goimports generated output:" ; echo "$d"; exit 1; fi
  staticcheck:
    name: staticheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go install honnef.co/go/tools/cmd/staticcheck
      - run: $HOME/go/bin/staticcheck ./...
  errcheck:
    name: errcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: go get -v github.com/kisielk/errcheck
      - run: set +e ; d="$($HOME/go/bin/errcheck -ignoretests -asserts -ignoregenerated ./... | grep -v internal)"; if [ -n "$d" ]; then echo "errcheck output:" ; echo "$d"; exit 1; else exit 0 ; fi ; set -e
  sec:
    name: sec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: go get -v github.com/securego/gosec/cmd/gosec
      - run: $HOME/go/bin/gosec -exclude=G101,G104,G204,G304 -exclude-dir ingester ./...
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - run: go get -v golang.org/x/lint/golint
      - run: set +e ; d="$($HOME/go/bin/golint -min_confidence 1 ./... | grep -v comment)" ; if [ -z "$d" ]; then exit 0 ; else echo "golint check output:" ; echo "$d" ; exit 1 ; fi ; set -e
