name: golang/static
on: pull_request

jobs:

  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: vet
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: vet
        comment: false
  
  # TODO: Enable linters below one by one and fix issues with each

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow
          comment: false

  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: imports
        comment: false

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: check
  #     uses: grandcolline/golang-github-actions@v1.1.0
  #     with:
  #       run: lint
  #       comment: false

  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@v1.1.0
      with:
        run: staticcheck
        flags: "-checks=\"inherit\",\"-SA4006\",\"-U1000\",\"-SA4009\""
        comment: true
        token: ${{ secrets.REPO_ACCESS_TOKEN }}


  # errcheck:
  #   name: Errcheck
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: check
  #     uses: grandcolline/golang-github-actions@v1.1.0
  #     with:
  #       run: errcheck
  #       comment: false

  # sec:
  #   name: Sec
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: check
  #     uses: grandcolline/golang-github-actions@v1.1.0
  #     with:
  #       run: sec
  #       flags: "-exclude=G104"
  #       comment: false
